# Generated by Django 5.2.7 on 2025-12-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-match_score']},
        ),
        migrations.AddField(
            model_name='careerpath',
            name='max_salary',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='min_salary',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
